name: Build IPA

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Select Xcode
        run: sudo xcode-select -s /Applications/Xcode.app

      - name: Run ipabuild.sh
        run: |
          chmod +x ipabuild.sh
          ./ipabuild.sh

      - name: Upload IPA Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Erosion-IPA
          path: "*.ipa"
